name: Azure Key Vault Secret Retrieval

on:
  workflow_dispatch:
    inputs:
      secretName:
        description: 'Name of the secret in Azure Key Vault'
        required: true
        default: 'mySuperSecret' # You can set a default secret name or leave this empty
      keyVaultName:
          description: 'Name of the Azure Key Vault'
          required: true
          default: 'gh-runner-demo-kv-001' # You can set a default name or leave this empty

permissions:
  id-token: write
  contents: read

jobs:
  retrieve-secret:
    runs-on: azure-linux-runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check IP
        run: curl https://api.ipify.org
